########################################################################
# Digital Health Portal
# Purpose: To Annotate the Data in Sleep Health Public Researcher Portal
# Author: Meghasyam Tummalacherla
# email: meghasyam@sagebase.org
########################################################################
##############
# Notes, Ideas, To-Dos
##############
### Note:
## To successfully run this code, you need write permissions to syn18492837
#
# Using https://docs.google.com/document/d/19VZ0dWVzFBnWj11xSU0seiFU0pFpVkRK/edit as list of annotations
#
##

##############
# Required libraries
##############
library(plyr)
library(tidyverse)
library(synapser)
synLogin()

study = 'SleepHealth Mobile App Study'
projectlink = paste("[", study, "](/Explore/Studies/DetailsPage?study=",
                    URLencode(study,  reserved = FALSE, repeated = FALSE), 
                    ")", sep = "")

##############
# List of tables and related annotations
##############
tables.annotations = list(
  # Alertness Checker - Psychomotor Vigilance Task
  'syn22271040' = list(consortium = 'mHealth',
                       study = study,
                       studyOrProject = projectlink,
                       numberParticipants= as.integer(4031), 
                       dataCollectionMethod= c('active'), 
                       diagnosis= c('control'),
                       deviceType = c('handheld'),
                       sensorType = c('touchscreen'),
                       devicePlatform = c('iOS'), 
                       deviceLocation = c('hand'),
                       reportedOutcome = c('reaction time'),
                       digitalAssessmentCategory= c('cognition'),
                       digitalAssessmentDetails = c('3-minute Psychomotor Vigilance Task (PVT-B)',
                                                    'tapping'),
                       dataType=c('sensor'),
                       dataSubtype=c('processed'),
                       # metadataType = c(''),
                       dhPortalIndex = 'FALSE',
                       dataDescriptionLocation = 'syn18492837/wiki/593722',
                       dataAccessInstructions = 'syn18492837/wiki/590794'),
  
  # Nap Tracker
  'syn22264428' = list(consortium = 'mHealth',
                       study = study,
                       studyOrProject = projectlink,
                       numberParticipants= as.integer(592), 
                       dataCollectionMethod= c('patient reported outcome'), 
                       diagnosis= c('control'),
                       # deviceType = c(''),
                       # sensorType = c(''),
                       # devicePlatform = c(''), 
                       # deviceLocation = c(''),
                       reportedOutcome = c('sleep report'),
                       # digitalAssessmentCategory= c(''),
                       # digitalAssessmentDetails = c(''),
                       dataType=c('surveyData'),
                       dataSubtype=c('raw'),
                       # metadataType = c(''),
                       dhPortalIndex = 'FALSE',
                       dataDescriptionLocation = 'syn18492837/wiki/593728',
                       dataAccessInstructions = 'syn18492837/wiki/590794'),
  
  # Sleepness Checker
  'syn22264418'= list(consortium = 'mHealth',
                      study = study,
                      studyOrProject = projectlink,
                      numberParticipants= as.integer(4636), 
                      dataCollectionMethod= c('patient reported outcome'),
                      diagnosis= c('control'),
                      # deviceType = c(''),
                      # sensorType = c(''),
                      # devicePlatform = c(''), 
                      # deviceLocation = c(''),
                      reportedOutcome = c('sleep report'),
                      # digitalAssessmentCategory= c(''),
                      # digitalAssessmentDetails = c(''),
                      dataType=c('surveyData'),
                      dataSubtype=c('raw'),
                      # metadataType = c(''),
                      dhPortalIndex = 'FALSE',
                      dataDescriptionLocation = 'syn18492837/wiki/593718',
                      dataAccessInstructions = 'syn18492837/wiki/590794'),
  
  # Sleep Quality Checker
  'syn22264412'= list(consortium = 'mHealth',
                      study = study,
                      studyOrProject = projectlink,
                      numberParticipants= as.integer(4566), 
                      dataCollectionMethod= c('patient reported outcome'),
                      diagnosis= c('control'),
                      # deviceType = c(''),
                      # sensorType = c(''),
                      # devicePlatform = c(''), 
                      # deviceLocation = c(''),
                      reportedOutcome = c('sleep report'),
                      # digitalAssessmentCategory= c(''),
                      # digitalAssessmentDetails = c(''),
                      dataType=c('surveyData'),
                      dataSubtype=c('raw'),
                      # metadataType = c(''),
                      dhPortalIndex = 'FALSE',
                      dataDescriptionLocation = 'syn18492837/wiki/593719',
                      dataAccessInstructions = 'syn18492837/wiki/590794'),
  
  # PM Check-in
  'syn22264410'= list(consortium = 'mHealth',
                      study = study,
                      studyOrProject = projectlink,
                      numberParticipants= as.integer(4313), 
                      dataCollectionMethod= c('patient reported outcome'),
                      diagnosis= c('control'),
                      # deviceType = c(''),
                      # sensorType = c(''),
                      # devicePlatform = c(''), 
                      # deviceLocation = c(''),
                      reportedOutcome = c('activity report'),
                      # digitalAssessmentCategory= c(''),
                      # digitalAssessmentDetails = c(''),
                      dataType=c('surveyData'),
                      dataSubtype=c('raw'),
                      # metadataType = c(''),
                      dhPortalIndex = 'FALSE',
                      dataDescriptionLocation = 'syn18492837/wiki/593726',
                      dataAccessInstructions = 'syn18492837/wiki/590794'),
  
  # AM Check-in
  'syn22264398'= list(consortium = 'mHealth',
                      study = study,
                      studyOrProject = projectlink,
                      numberParticipants= as.integer(5266), 
                      dataCollectionMethod= c('patient reported outcome'),
                      diagnosis= c('control'),
                      # deviceType = c(''),
                      # sensorType = c(''),
                      # devicePlatform = c(''), 
                      # deviceLocation = c(''),
                      reportedOutcome = c('sleep report'),
                      # digitalAssessmentCategory= c(''),
                      # digitalAssessmentDetails = c(''),
                      dataType=c('surveyData'),
                      dataSubtype=c('raw'),
                      # metadataType = c(''),
                      dhPortalIndex = 'FALSE',
                      dataDescriptionLocation = 'syn18492837/wiki/593723',
                      dataAccessInstructions = 'syn18492837/wiki/590794'),
  
  # My Health
  'syn22264395'= list(consortium = 'mHealth',
                      study = study,
                      studyOrProject = projectlink,
                      numberParticipants= as.integer(1478), 
                      dataCollectionMethod= c('patient reported outcome'),
                      diagnosis= c('control'),
                      # deviceType = c(''),
                      # sensorType = c(''),
                      # devicePlatform = c(''), 
                      # deviceLocation = c(''),
                      reportedOutcome = c('medical history'),
                      # digitalAssessmentCategory= c(''),
                      # digitalAssessmentDetails = c(''),
                      dataType=c('surveyData'),
                      dataSubtype=c('raw'),
                      # metadataType = c(''),
                      dhPortalIndex = 'FALSE',
                      dataDescriptionLocation = 'syn18492837/wiki/593707',
                      dataAccessInstructions = 'syn18492837/wiki/590794'),
  
  # Sleep Habits
  'syn22264326'= list(consortium = 'mHealth',
                      study = study,
                      studyOrProject = projectlink,
                      numberParticipants= as.integer(3155), 
                      dataCollectionMethod= c('patient reported outcome'),
                      diagnosis= c('control'),
                      # deviceType = c(''),
                      # sensorType = c(''),
                      # devicePlatform = c(''), 
                      # deviceLocation = c(''),
                      reportedOutcome = c('sleep report'), 
                      # digitalAssessmentCategory= c(''),
                      # digitalAssessmentDetails = c(''),
                      dataType=c('surveyData'),
                      dataSubtype=c('raw'),
                      # metadataType = c(''),
                      dhPortalIndex = 'FALSE',
                      dataDescriptionLocation = 'syn18492837/wiki/593720',
                      dataAccessInstructions = 'syn18492837/wiki/590794'),
  
  # About Me
  'syn22264269'= list(consortium = 'mHealth',
                      study = study,
                      studyOrProject = projectlink,
                      numberParticipants= as.integer(3262), 
                      dataCollectionMethod= c('patient reported outcome'),
                      diagnosis= c('control'),
                      # deviceType = c(''),
                      # sensorType = c(''),
                      # devicePlatform = c(''), 
                      # deviceLocation = c(''),
                      reportedOutcome = c('quality of life'),
                      # digitalAssessmentCategory= c(''),
                      # digitalAssessmentDetails = c(''),
                      dataType=c('surveyData'),
                      dataSubtype=c('raw'),
                      # metadataType = c(''),
                      dhPortalIndex = 'FALSE',
                      dataDescriptionLocation = 'syn18492837/wiki/592581',
                      dataAccessInstructions = 'syn18492837/wiki/590794'),
  
  # Onboarding Demographics
  'syn22264195'= list(consortium = 'mHealth',
                      study = study,
                      studyOrProject = projectlink,
                      numberParticipants= as.integer(7250), 
                      dataCollectionMethod= c('patient reported outcome'),
                      diagnosis= c('control'),
                      # deviceType = c(''),
                      # sensorType = c(''),
                      # devicePlatform = c(''), 
                      # deviceLocation = c(''),
                      reportedOutcome = c('demographics survey'),
                      # digitalAssessmentCategory= c(''),
                      # digitalAssessmentDetails = c(''),
                      dataType=c('surveyData'),
                      dataSubtype=c('raw'),
                      # metadataType = c(''),
                      dhPortalIndex = 'FALSE',
                      dataDescriptionLocation = 'syn18492837/wiki/590798',
                      dataAccessInstructions = 'syn18492837/wiki/590794'),
  
  # Sleep Assessment
  'syn21966546'= list(consortium = 'mHealth',
                      study = study,
                      studyOrProject = projectlink,
                      numberParticipants= as.integer(2228), 
                      dataCollectionMethod= c('patient reported outcome'),
                      diagnosis= c('control'),
                      # deviceType = c(''),
                      # sensorType = c(''),
                      # devicePlatform = c(''), 
                      # deviceLocation = c(''),
                      reportedOutcome = c('sleep report'),
                      # digitalAssessmentCategory= c(''),
                      # digitalAssessmentDetails = c(''),
                      dataType=c('surveyData'),
                      dataSubtype=c('raw'),
                      # metadataType = c(''),
                      dhPortalIndex = 'FALSE',
                      dataDescriptionLocation = 'syn18492837/wiki/593721',
                      dataAccessInstructions = 'syn18492837/wiki/590794'),
  
  # Research Interest
  'syn21966541'= list(consortium = 'mHealth',
                      study = study,
                      studyOrProject = projectlink,
                      numberParticipants= as.integer(2192), 
                      dataCollectionMethod= c('patient reported outcome'),
                      diagnosis= c('control'),
                      # deviceType = c(''),
                      # sensorType = c(''),
                      # devicePlatform = c(''), 
                      # deviceLocation = c(''),
                      reportedOutcome = c('research interest'), 
                      # digitalAssessmentCategory= c(''),
                      # digitalAssessmentDetails = c(''),
                      dataType=c('surveyData'),
                      dataSubtype=c('raw'),
                      # metadataType = c(''),
                      dhPortalIndex = 'FALSE',
                      dataDescriptionLocation = 'syn18492837/wiki/593711',
                      dataAccessInstructions = 'syn18492837/wiki/590794'),
  
  # My Family
  'syn21966449'= list(consortium = 'mHealth',
                      study = study,
                      studyOrProject = projectlink,
                      numberParticipants= as.integer(2760), 
                      dataCollectionMethod= c('patient reported outcome'),
                      diagnosis= c('control'),
                      # deviceType = c(''),
                      # sensorType = c(''),
                      # devicePlatform = c(''), 
                      # deviceLocation = c(''),
                      reportedOutcome = c('family history'), 
                      # digitalAssessmentCategory= c(''),
                      # digitalAssessmentDetails = c(''),
                      dataType=c('surveyData'),
                      dataSubtype=c('raw'),
                      # metadataType = c(''),
                      dhPortalIndex = 'FALSE',
                      dataDescriptionLocation = 'syn18492837/wiki/593712',
                      dataAccessInstructions = 'syn18492837/wiki/590794'),
  
  # HealthKit.StepCount
  'syn21963204'= list(consortium = 'mHealth',
                      study = study,
                      studyOrProject = projectlink,
                      numberParticipants= as.integer(2592), 
                      dataCollectionMethod= c('passive'),
                      diagnosis= c('control'),
                      deviceType = c('handheld', 'wearable'),
                      sensorType = c('accelerometer', 'gyroscope', 'pedometer'), 
                      devicePlatform = c('iOS'), 
                      deviceLocation = c('pocket', 'wrist'),
                      # reportedOutcome = c(''),
                      digitalAssessmentCategory= c('physical activity'),
                      digitalAssessmentDetails = c('daily physical activity', 'step count'),
                      dataType=c('sensor'),
                      dataSubtype=c('processed', 'metadata'),
                      metadataType = c('data dictionary', 'assessment'),
                      dhPortalIndex = 'FALSE',
                      dataDescriptionLocation = 'syn18492837/wiki/601925',
                      dataAccessInstructions = 'syn18492837/wiki/590794'),
  
  # HealthKit.Height
  'syn21963203'= list(consortium = 'mHealth',
                      study = study,
                      studyOrProject = projectlink,
                      numberParticipants= as.integer(1933), 
                      dataCollectionMethod= c('patient reported outcome'),
                      diagnosis= c('control'),
                      # deviceType = c(''),
                      # sensorType = c(''),
                      # devicePlatform = c(''), 
                      # deviceLocation = c(''),
                      reportedOutcome = c('height'), 
                      # digitalAssessmentCategory= c(''),
                      # digitalAssessmentDetails = c(''),
                      dataType=c('surveyData'),
                      dataSubtype=c('raw', 'metadata'),
                      metadataType = c('data dictionary', 'assessment'),
                      dhPortalIndex = 'FALSE',
                      dataDescriptionLocation = 'syn18492837/wiki/601925',
                      dataAccessInstructions = 'syn18492837/wiki/590794'),
  
  # HealthKit.HeartRate
  'syn21963196'= list(consortium = 'mHealth',
                      study = study,
                      studyOrProject = projectlink,
                      numberParticipants= as.integer(2012), 
                      dataCollectionMethod= c('passive'),
                      diagnosis= c('control'),
                      deviceType = c('handheld', 'wearable'),
                      sensorType = c('photosensor'),
                      devicePlatform = c('iOS'), 
                      deviceLocation = c('hand', 'wrist'), 
                      # reportedOutcome = c('heart rate'),
                      digitalAssessmentCategory= c('cardiovascular'),
                      digitalAssessmentDetails = c('heart rate'),
                      dataType=c('sensor'),
                      dataSubtype=c('processed', 'metadata'),
                      metadataType = c('data dictionary', 'assessment'),
                      dhPortalIndex = 'FALSE',
                      dataDescriptionLocation = 'syn18492837/wiki/601925',
                      dataAccessInstructions = 'syn18492837/wiki/590794'),
  
  
  # HealthKit.FlightsClimbed
  'syn21963195'= list(consortium = 'mHealth',
                      study = study,
                      studyOrProject = projectlink,
                      numberParticipants= as.integer(1537), 
                      dataCollectionMethod= c('passive'),
                      diagnosis= c('control'),
                      deviceType = c('handheld', 'wearable'),
                      sensorType = c('accelerometer', 'gyroscope'),
                      devicePlatform = c('iOS'), 
                      deviceLocation = c('pocket', 'wrist'),
                      # reportedOutcome = c(''),
                      digitalAssessmentCategory= c('physical activity'),
                      digitalAssessmentDetails = c('daily physical activity', 'flights climbed'),
                      dataType=c('sensor'),
                      dataSubtype=c('processed', 'metadata'),
                      metadataType = c('data dictionary', 'assessment'),
                      dhPortalIndex = 'FALSE',
                      dataDescriptionLocation = 'syn18492837/wiki/601925',
                      dataAccessInstructions = 'syn18492837/wiki/590794'),
  
  # HealthKit.DistanceWalkingRunning
  'syn21962791'= list(consortium = 'mHealth',
                      study = study,
                      studyOrProject = projectlink,
                      numberParticipants= as.integer(2480), 
                      dataCollectionMethod= c('passive'),
                      diagnosis= c('control'),
                      deviceType = c('handheld', 'wearable'),
                      sensorType = c('pedometer', 'accelerometer' ), 
                      devicePlatform = c('iOS'), 
                      deviceLocation = c('pocket', 'wrist'),
                      # reportedOutcome = c(''),
                      digitalAssessmentCategory= c('physical activity'),
                      digitalAssessmentDetails = c('daily physical activity', 'distance'),
                      dataType=c('sensor'),
                      dataSubtype=c('processed', 'metadata'),
                      metadataType = c('data dictionary', 'assessment'),
                      dhPortalIndex = 'FALSE',
                      dataDescriptionLocation = 'syn18492837/wiki/601925',
                      dataAccessInstructions = 'syn18492837/wiki/590794'),
  
  # HealthKit.BodyMass
  'syn21962784'= list(consortium = 'mHealth',
                      study = study,
                      studyOrProject = projectlink,
                      numberParticipants= as.integer(2014), 
                      dataCollectionMethod= c('patient reported outcome'),
                      diagnosis= c('control'),
                      # deviceType = c(''),
                      # sensorType = c(''),
                      # devicePlatform = c(''), 
                      # deviceLocation = c(''),
                      reportedOutcome = c('weight'),
                      # digitalAssessmentCategory= c(''),
                      # digitalAssessmentDetails = c(''),
                      dataType=c('surveyData'),
                      dataSubtype=c('raw', 'metadata'),
                      metadataType = c('data dictionary', 'assessment'),
                      dhPortalIndex = 'FALSE',
                      dataDescriptionLocation = 'syn18492837/wiki/601925',
                      dataAccessInstructions = 'syn18492837/wiki/590794'),
  
  # HealthKit.BasalEnergyBurned
  'syn21962783'= list(consortium = 'mHealth',
                      study = study,
                      studyOrProject = projectlink,
                      numberParticipants= as.integer(752), 
                      dataCollectionMethod= c('passive'),
                      diagnosis= c('control'),
                      deviceType = c('handheld', 'wearable'),
                      sensorType = c('accelerometer', 'gyroscope'),
                      devicePlatform = c('iOS'), 
                      deviceLocation = c('pocket', 'wrist'),
                      # reportedOutcome = c(''), 
                      digitalAssessmentCategory= c('physical activity'),
                      digitalAssessmentDetails = c('daily physical activity', 'resting energy burned'),
                      dataType=c('sensor'),
                      dataSubtype=c('processed', 'metadata'),
                      metadataType = c('data dictionary', 'assessment'),
                      dhPortalIndex = 'FALSE',
                      dataDescriptionLocation = 'syn18492837/wiki/601925',
                      dataAccessInstructions = 'syn18492837/wiki/590794'),
  
  # HealthKit.AppleExerciseTime
  'syn21962782'= list(consortium = 'mHealth',
                      study = study,
                      studyOrProject = projectlink,
                      numberParticipants= as.integer(467), 
                      dataCollectionMethod= c('passive'),
                      diagnosis= c('control'),
                      deviceType = c('handheld', 'wearable'),
                      sensorType = c('accelerometer', 'gyroscope'), 
                      devicePlatform = c('iOS'), 
                      deviceLocation = c('pocket', 'wrist'),
                      # reportedOutcome = c(''),
                      digitalAssessmentCategory= c('physical activity'),
                      digitalAssessmentDetails = c('daily physical activity', 'exercise time'),
                      dataType=c('sensor'),
                      dataSubtype=c('processed', 'metadata'),
                      metadataType = c('data dictionary', 'assessment'),
                      dhPortalIndex = 'FALSE',
                      dataDescriptionLocation = 'syn18492837/wiki/601925',
                      dataAccessInstructions = 'syn18492837/wiki/590794'),
  
  # HealthKit.ActiveEnergyBurned
  'syn21962781'= list(consortium = 'mHealth',
                      study = study,
                      studyOrProject = projectlink,
                      numberParticipants= as.integer(563), 
                      dataCollectionMethod= c('passive'),
                      diagnosis= c('control'),
                      deviceType = c('handheld', 'wearable'),
                      sensorType = c('acceleromter', 'gyroscope'),
                      devicePlatform = c('iOS'), 
                      deviceLocation = c('pocket', 'wrist'),
                      # reportedOutcome = c(''), 
                      digitalAssessmentCategory= c('physical activity'),
                      digitalAssessmentDetails = c('daily physical activity', 'active energy burned'),
                      dataType=c('sensor'),
                      dataSubtype=c('processed', 'metadata'),
                      metadataType = c('data dictionary', 'assessment'),
                      dhPortalIndex = 'FALSE',
                      dataDescriptionLocation = 'syn18492837/wiki/601925',
                      dataAccessInstructions = 'syn18492837/wiki/590794')
  
  
)

#################
# Now set annotations
#################
projects.list =  names(tables.annotations)
for(proj.id in projects.list){
  
  #### Uncomment this before updating for real
  # synSetAnnotations(proj.id, annotations = tables.annotations[[proj.id]])
  ####
  
  print(proj.id)
  print(tables.annotations[[proj.id]])
}


##################
# Set annotations of individual files
##################
## There are NO INDIVIDUAL FILES in this study